### PR TITLE
Ocius and Worship Press Release

### PR DESCRIPTION
**Pull request by cjmoses**
Press release

### CODE REVIEW

**Review by r007 — CHANGES_REQUESTED** [review]
Can you please use a bigger picture?

**Comment by Kevinwochan** [comment]
@r007 Hi sergei, @cjmoses is taking over publishing news/media coverage.

**Comment by r007** [comment]
@Kevinwochan hey Kevin :) @cjmoses It's nice to meet you, Cameron!

**Review by r007 — APPROVED** [review]
Article looks good

**Comment by cjmoses** [comment]
Hi Sergei,

I just made an update to the copy that the guys required. Can you check all
good to push live tomorrow.

Thanks,
Cameron

**Pull request merged**
