### PR TITLE
Kevin

### PR DESCRIPTION
**Pull request by Kevinwochan**
[stage.pdf](https://github.com/ocius/website/files/4026270/stage.pdf)
[kevin.pdf](https://github.com/ocius/website/files/4026271/kevin.pdf)

Increasing the size of the landing wallpaper decreases our performance score but it helps to make the website look much more professional.

What are your opinions? is it worth it?

### CODE REVIEW

**Comment by Kevinwochan** [comment]
@r007 Thanks for catching that!
I've removed the outbound button code for now to keep it simple.

**Comment by r007** [comment]
@Kevinwochan take a look, I adjusted color levels to make image brighter. Not commited to repository yet.

_Before_
before1

_After_
after1

drone_boat_32

What do you think? Text might be needed some rework to make it more readable.

Also, I've made article titles bigger.

lay

**Comment by Kevinwochan** [comment]
@r007 I see what you mean by too dark, this is brilliant! 
Commit the changes and i'll  preview all these changes to Robert once it's up.

**Comment by r007** [comment]
@Kevinwochan thanks. Done, all the changes are commited to 'Kevin' branch.

Here's the current version:

with-bg

I removed text shadows and added light blue scrim to the top. Here's how it looks like without background image:

without-bg

It looks fresh and very natural at the same time. By the way, the "What is a USV" button stopped working on the home page.

**Comment by r007** [comment]
Done, fixed buttons everywhere.

**Pull request closed without merging**
