### PR TITLE
Update info

### PR DESCRIPTION
**Pull request by Kevinwochan**
https://github.com/ocius/website/issues/196

### CODE REVIEW

**Comment by r007** [comment]
Please don't do that - instead of classes just use the functional style. They are more elegant. I refactored your code to functional style. The "last updated" time is not very accurate. It shows the time incorrectly, like "25 minutes ago", must be an error somewhere.

**Review by r007 — CHANGES_REQUESTED** [review]
Please fix the time

**Comment by Kevinwochan** [comment]
> Please fix the time

@r007 yes that looks strange but it's actually accurate. 
Currently information goes from Drone -> Server -> Browser
"Last updated" displays the last time the drone communicated with our servers (usually every 30mins). 
The green highlight displays the last time the browser communicated with the server.

> Please don't do that - instead of classes just use the functional style. They are more elegant. I refactored your code to functional style. The "last updated" time is not very accurate. It shows the time incorrectly, like "25 minutes ago", must be an error somewhere.

I attempted to do this functional style but component state changes unfortunately cause component updates. This forced me to use getDerivedStateFromProps which is only available using react classes. 

Here is my desired output:
desired
Note how the components flashes green in time with each HTTP request

However using functional style, we can only remove the flash after every second update.
off

**Comment by Kevinwochan** [comment]
actually, i think i might have a way to do this functional style

**Comment by Kevinwochan** [comment]
@r007 bump 👍

**Comment by r007** [comment]
@Kevinwochan actually that's not the case. The only bug here it's here:

```javascript
// This state is "upToDate" only when lastUpdate prop is changed
setUpToDate(lastUpdatedState !== lastUpdated);
setLastUpdateState(lastUpdated);

// Start timer only if prop data was updated
if (!upToDate) return;
```
The ```setUpToDate()``` function is asynchronous and the variable ```upToDate``` gets checked before it changes its value. For example:

```javascript
// The state before was 'false'
setUpToDate(true);

// Still counted as 'false'
if (!upToDate) return;
```
I refactored the code, now it should work fine :)

**Review by r007 — APPROVED** [review]
Seems like bug is gone

**Pull request merged**
