### PR TITLE
Move articles to media coverage page

### PR DESCRIPTION
**Pull request by r007**

### CODE REVIEW

**Comment by thomasdane** [comment]
LGTM. Until we get a designer though, before merging @Kevinwochan could you show all changes to Robert on the respective staging environments? Sergey's or yours, and get approval?

**Comment by r007** [comment]
Done, I've sent the email.

**Comment by thomasdane** [comment]
@r007 if Robert approved, go ahead and merge!

**Comment by r007** [comment]
@thomasdane I'm not authorized to merge.

**Pull request merged**
