### PR TITLE
removed advanced view button and centered ocius logo

### PR DESCRIPTION
**Pull request by Kevinwochan**
#179
#177

### CODE REVIEW

**Comment by r007** [comment]
Wait, why did you remove the splash screen? It was requested by Tom.

**Comment by Kevinwochan** [comment]
> Wait, why did you remove the splash screen? It was requested by Tom.

My bad! i got abit zealous deleting references to the advanced button. Should be fixed in the next commit.
https://kevin.d3fhwa1e0f950h.amplifyapp.com/

> Also, I think you can use `transform: translateX(-50%)` instead of `transform: translateX(-2.5rem)`
yeah i don't like how i've hardcoded as '-2.5rem'. I wanted to ignore the width taken up the menu button.

**Comment by r007** [comment]
Actually... Yeah, you're right. Hardcoded value should be fine here.

**Comment by Kevinwochan** [comment]
Thanks again for picking up on the splash screen removal. That would have gone to production without you.

**Pull request merged**
