### PR TITLE
Hsl string

### PR DESCRIPTION
**Pull request by Kevinwochan**
image

### CODE REVIEW

**Comment by Kevinwochan** [comment]
@r007 what do you think?

**Comment by r007** [comment]
Hey @Kevinwochan! I like it. Just a couple notes from me:

No need to hardcode the max temperature value, you can just pass the default value so that you can change it later:

```javascript
 const RainbowColor = (currentTemperature, minTemperature = 11, maxTemperature = 29) => { };
```

 Agree, colors are a bit strong. Here's the HUE wheel:
ak7Lu

It makes sense to only use color range between 20 degrees and 170 degrees. Red color is very strong here. I think we can calculate colors like this:
```javascript
let i = (currentTemperature * 150 / maxTemperature) + 20;
```
Where:
- ```20``` is the color shift, we want to shift the color wheel by 20 degrees.
- ```150 + 20 = 170``` is the max value on the color wheel.

Thus, everything should start from 20. If temperature is higher than 28 degrees:

```javascript
// Add 20 deg color shift
if (currentTemperature >= maxTemperature) i = 20;
if (currentTemperature <= minTemperature) i = 170;
```
That's basically it, should be good enough.

**Comment by Kevinwochan** [comment]
@r007 implemented!
that hue wheel was super helpful, I did expand your suggested colour range so the 21-13 range was more distinct. 

From 
Screenshot from 2020-09-28 09-22-42
To
Screenshot from 2020-09-28 09-27-33

**Comment by Kevinwochan** [comment]
Once this goes through i'll demo to Robert and Chris.

**Comment by r007** [comment]
@Kevinwochan niiice, thanks! Everything looks good now.

**Pull request merged**
