### PR TITLE
Boat colors

### PR DESCRIPTION
**Pull request by Kevinwochan**
Matching colours at https://usvna.ocius.com.au/usvna/oc_server

To make the colours standout i'll see how to create a white/black outline around the text.

### CODE REVIEW

**Comment by thomasdane** [comment]
Nice work Kevin! @r007 let us know what you think of these changes. @Kevinwochan I might create you your own branch that will be deployed to AMP for testing.

**Comment by r007** [comment]
Code looks good, but like I said, boat name will be overlapping with its own trail (shown on the picture).

szoter_annotated_image(8)

Make sense to keep distinctive color.

**Comment by thomasdane** [comment]
@Kevinwochan @r007 discussion about other options here: give the boat name a background color? Make them complimentary colours? Make the name always white or black?

**Comment by Kevinwochan** [comment]
I'll give those a shot, closing this PR for now

**Pull request closed without merging**
