### PR TITLE
News

### PR DESCRIPTION
**Pull request by Kevinwochan**
I haven't been able to get the news blogs to render. when opening any news post a blank page is served. This is progress from being unable to run "gatsby develop" though.

image

Please verify that the formatting for the August 2019 update looks okay.

### CODE REVIEW

**Comment by r007** [comment]
Please open the dev panel (F12 - Console tab). What does it say?

**Comment by Kevinwochan** [comment]
Weirdly, no console log errors
image

**Comment by Kevinwochan** [comment]
After running ```gatsby develop``` and loading any page for the first time, i get this error
image

**Comment by r007** [comment]
It's fine. These are prop types errors, I'll fix them later. Have you tried hard refresh - Ctrl+F5? It should help I think.

**Comment by Kevinwochan** [comment]
I followed this https://www.getfilecloud.com/blog/2015/03/tech-tip-how-to-do-hard-refresh-in-browsers/
and tried both "Hard Reload" and  "Empty Cache and Hard Reload", no luck.

**Comment by Kevinwochan** [comment]
running ```gatsby build``` to generate the HTML works fine
image

**Comment by r007** [comment]
Try the following:
1. Private mode in browser (Ctrl+Shift+P).
2. Try to open in different browser.
3. ```gatsby start``` instead of ```gatsby develop```.

**Pull request merged**
