### PR TITLE
 added default infowindow contents

### PR DESCRIPTION
**Pull request by Kevinwochan**
I added a black html div so that the info windows had some content inside when the Cameras were offline.

### CODE REVIEW

**Comment by Kevinwochan** [comment]
@r007 i have updates for the about page ready for review. Should i wait for the next PR?

**Comment by r007** [comment]
@Kevinwochan sorry for the late reply. Can you attach the screenshot of end result?

**Comment by Kevinwochan** [comment]
Thanks for reminding me to have another look, there was uncommitted code in my local source. I'll push that now.

**Comment by Kevinwochan** [comment]
@r007 bump :smile:

**Comment by r007** [comment]
@Kevinwochan looks good. Even though I usually prefer to avoid hardcoded positions and widths, and I'd usually go with something like position: absolute; with left, right, top, bottom set to 0. But in this case, might be dangerous to use this approach, hardcoded option seems to be "safer". So let's just merge it into the master.

**Pull request merged**
