### PR TITLE
News release

### PR DESCRIPTION
**Pull request by Kevinwochan**
https://github.com/ocius/website/issues/191

### CODE REVIEW

**Review by r007 — APPROVED** [review]
Looks good

**Comment by r007** [comment]
@Kevinwochan can be cleaned up a little bit, duplicated ```<iframe iframe>...``` is not really needed

**Comment by Kevinwochan** [comment]
@r007  i'll make a new PR to fix that.
You wonderful man, thanks for reviewing this so quickly.

**Comment by r007** [comment]
@Kevinwochan thanks. No problem, still need to dedicate some time to clean up all these issues... *sigh*

**Pull request merged**
