### PR TITLE
Website redesign

### PR DESCRIPTION
**Pull request by Kevinwochan**
Enabling Amplify Preview

### CODE REVIEW

**Comment by Kevinwochan** [comment]
I will run these commands before merging this PR
```
git checkout master
git reset --hard 80ed09f02387919e1d7abd3f181af456a44b9b8f
git push --force
```

**Comment by r007** [comment]
@Kevinwochan done, finished USV page, check this out --> https://pr-226.d3fhwa1e0f950h.amplifyapp.com/usv/

**Comment by r007** [comment]
@Kevinwochan one more page is done --> https://pr-226.d3fhwa1e0f950h.amplifyapp.com/news 
Just a few pages left - Contact Us, Careers and Media Coverage mostly

**Comment by r007** [comment]
@Kevinwochan media coverage page is done --> https://pr-226.d3fhwa1e0f950h.amplifyapp.com/media-coverage
I added the AJAX pagination as well

**Comment by r007** [comment]
@Kevinwochan done, the contact page is mostly done. I even added the microdata for contact information. Now we need Tom to deploy lambda function to make contact form functional.

Not sure about "get directions" button, will try to implement it later.

**Comment by Kevinwochan** [comment]
> 
> 
> @Kevinwochan done, the contact page is mostly done. I even added the microdata for contact information. Now we need Tom to deploy lambda function to make contact form functional.
> 
> Not sure about "get directions" button, will try to implement it later.

I'll make sure we test the contact form on Monday. 
It looks exactly like Chris' design!

About page needs to optimised abit for mobile: 
image

**Comment by r007** [comment]
@Kevinwochan thanks. By the way, lambda function is in the 'contactmailer' directory. It is ready for test.

I know. Next steps are:
1) Small fixes - for example, buttons doesn't work here and there.
2) Optimization for small screens aka smartphones/tablets. Mobile menu is not done yet.
3) Speed optimization of the website.

**Comment by Kevinwochan** [comment]
> 
> 
> @Kevinwochan thanks. By the way, lambda function is in the 'contactmailer' directory. It is ready for test.
> 
> I know. Next steps are:
> 
>     1. Small fixes - for example, buttons doesn't work here and there.
> 
>     2. Optimization for small screens aka smartphones/tablets. Mobile menu is not done yet.
> 
>     3. Speed optimization of the website.

Awesome! once that''s done I'll set up a time with Chris to review everything and click all the buttons.

**Comment by Kevinwochan** [comment]
@r007 tested the contact form yesterday 👍 no problems.
We will test again once this PR is in production

**Comment by r007** [comment]
@Kevinwochan hey 😃 I finished, this branch can be merged finally. Website is kicking some ass now.

There are tons of new changes:
- Navbar links now are not hardcoded now, they are queried using GraphQL from YAML file (see */src/data/nav/nav-items.yaml*). I fully refactored all navbar components.
- Carbon components are refactored into styled-components and removed from the project completely.
- Instead of hardcoded colors, website is using styled-components ThemeProvider.
- Fixed some memory leaks/small bugs.
- Further optimizations for mobile devices/tablets.
- **New component** was added SideNav ⭐

sidenav

**Review by r007 — DISMISSED** [review]
Approved by Robert

**Review by r007 — DISMISSED** [review]

**Comment by Kevinwochan** [comment]
@r007 😄 Just got added back to the repo. Still looking to remove my commits to master first.

**Review by r007 — APPROVED** [review]

**Pull request merged**
