### PR TITLE
Update README file

### PR DESCRIPTION
**Pull request by r007**

### CODE REVIEW

**Comment by r007** [comment]
It's just the README, other commit are already included in ```master```.

**Comment by Kevinwochan** [comment]
@r007 Looks like the build status badge is broken, other than that do you want me to merge this in?

**Comment by r007** [comment]
@Kevinwochan yes, please do.

**Comment by Kevinwochan** [comment]
hmm i didn't realise i wouldn't be able to approve this PR if i commited, i'll get Tom to merge this.

**Comment by r007** [comment]
Maybe we'll just close this PR? Can you update just the README please? And I'll approve.

**Comment by Kevinwochan** [comment]
sounds good

**Comment by r007** [comment]
Thanks!

**Pull request closed without merging**
