### PR TITLE
Website redesign stage 1

### PR DESCRIPTION
**Pull request by Kevinwochan**
This is a preliminary merge of the website redesign.

### CODE REVIEW

**Comment by Kevinwochan** [comment]
@r007 I'm going to merge this into master. When you're done implementing website-redesign, I'll detach the head of master to your last commit, update master with website-redesign then force push over my hacks.

**Comment by r007** [comment]
@Kevinwochan damn. The code is not quite ready for merge.

**Comment by Kevinwochan** [comment]
> 
> 
> @Kevinwochan damn. The code is not quite ready for merge.

@r007 yes, this is definitely a rushed job. Do you have time to review?
I was thinking, once you finish your implementation we throw all this code away.

**Comment by r007** [comment]
@Kevinwochan yep. I'm working on it today, I implemented the waves yesterday. Now working on the USV page.

**Comment by Kevinwochan** [comment]
@r007 any big issues with this going into production for now?
 It's the 26th of November 1:30AM in Australia at the moment, the day we expect traffic to come through.

**Comment by r007** [comment]
@Kevinwochan website is not very responsive yet. Especially on mobile. And 5 pages still left.

**Comment by Kevinwochan** [comment]
@r007 Which pages in particular don't seem responsive yet? I'll fix it up over the next few hours.
Currently these are the issues i've noticed:

- usv page text is left aligned on mobile
- the about page sections needs navtabs for navigation on mobile
- the media-cover page needs navtabs for navigation on mobile
- the news page needs navtabs for navigation on mobile

Again, once you finish your work on https://github.com/ocius/website/pull/226. I'll run these commands on master:
```
git reset --hard 80ed09f02387919e1d7abd3f181af456a44b9b8f
git merge website-redesign
git push --force
```

**Comment by r007** [comment]
@Kevinwochan I think about pages not very responsive... Need to find a mobile design files, which I believe Chris sent me before. They should be somewhere in the inbox...

**Comment by Kevinwochan** [comment]
@r007 looks good enough to me.

**Comment by Kevinwochan** [comment]
@r007 thanks for looking it over :smile:. Let's get these commits out of master asap :laughing:

**Pull request merged**
