### PR TITLE
A bunch of changes: popup, new blog layout, links to press kit, etc

### PR DESCRIPTION
**Pull request by r007**
Right now this pull request consists of:

- Updated hero background image
- Updated blog layout
- Add rotating loading text to live page
- Close popup when user clicks on map (live page)
- Add links to press kit (navbar)
- Add ability to put articles into draft
- Add sitemap
- Other misc changes...

### CODE REVIEW

**Comment by thomasdane** [comment]
@Kevinwochan when you get a chance, can you confirm with Robert on mobile and desktop that this works on ocius.stage?

**Comment by thomasdane** [comment]
@Kevinwochan once this is tested on stage, I'm happy for you to approve and merge.

**Comment by Kevinwochan** [comment]
@thomasdane The popup doesn't seem to be appearing, is that related to this bug? (https://github.com/ocius/website/issues/104). 

Peek 2020-01-22 12-27

**Comment by r007** [comment]
@Kevinwochan yes, exactly. The nasty bug with one drone, it appears occasionally. I can filter results on the client side, but Tom promised to resolve this problem. Will see.

**Comment by thomasdane** [comment]
@r007  @Kevinwochan the bug with duplicate drones is now fixed server side

**Pull request merged**
