### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by cjmoses**
Updates from Colin. Waiting on another image to add to post.

### CODE REVIEW

**Comment by cjmoses** [comment]
Updated as per Colin’s updates to the article.

**Comment by r007** [comment]
Ok, tell me when you're ready.

**Comment by cjmoses** [comment]
Have added the new image so is ready to publish now. Thanks!

**Comment by cjmoses** [comment]
Hi Sergey, sorry I think I was updating on the master branch and not the
news branch. I just updated the copy and image again and also removed the
quote formatting as it looked bad on mobile. The new pull request is #241,
sorry for any confusion.

**Comment by cjmoses** [comment]
Hi Sergei, just checking if you have approved the update to the article yet?


Thanks,


Cameron
m: 0402 246 785


The contents of this email are strictly confidential. If you are not the intended recipient, any use, disclosure, retention, printing or copying of this email (including any attachments) is unauthorised and prohibited. Please notify the sender and delete this email and any attachments immediately.

**Review by r007 — APPROVED** [review]
The article looks good

**Comment by r007** [comment]
@cjmoses please don't create too many branches. There is existing branch for blog articles, it's called "news". You can publish new articles on that branch, otherwise it makes so much harder for me to track changes you've made. Thanks.

**Comment by r007** [comment]
It's very confusing.

**Comment by cjmoses** [comment]
Yes sorry I thought I was in the news branch. 

Thanks,


Cameron
m: 0402 246 785


The contents of this email are strictly confidential. If you are not the intended recipient, any use, disclosure, retention, printing or copying of this email (including any attachments) is unauthorised and prohibited. Please notify the sender and delete this email and any attachments immediately.

**Pull request merged**
