### PR TITLE
added sales catalogue to news

### PR DESCRIPTION
**Pull request by Kevinwochan**

### CODE REVIEW

**Comment by Kevinwochan** [comment]
@r007 i just thought of one more addition, i'll quickly commit that now and make sure it works

**Comment by r007** [comment]
@Kevinwochan sure, but then maybe add just one thing - an author name to header?

**Comment by Kevinwochan** [comment]
@r007 if that looks good to you, i think merge it. 
I'm not authorised to merge MRs.

**Comment by r007** [comment]
@Kevinwochan I'm not authorized as well :\

merge

**Comment by Kevinwochan** [comment]
@r007 Toms updated the repo so you and i can both Merge.
In future i'll be sure to let you review+merge before any changes go through.

**Pull request merged**
