### PR TITLE
Announcing dih contract

### PR DESCRIPTION
**Pull request by Kevinwochan**
@r007 some really exciting news for the company!

https://www.minister.defence.gov.au/minister/melissa-price/media-releases/growing-australias-defence-industry-through-innovation

### CODE REVIEW

**Comment by r007** [comment]
@Kevinwochan oh wow, that's nice! Very glad for you, guys!

**Comment by r007** [comment]
@Kevinwochan **featuredImage** path is incorrect, can we fix that?

**Comment by Kevinwochan** [comment]
@r007 yes, my bad. I'll create a new PR.
The image within the article also appears broken in production.

**Comment by Kevinwochan** [comment]
@r007 i know what i did, i changed the file names while hotloading gatsby develop, the images appeared fine because they were cached.

**Pull request merged**
